# -*- coding: utf-8 -*-
"""Paladium_Data_Set_Limpio

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11PNil2G-r0TS0HCqoR-V542n65Xu-Phj
"""

!pip install streamlit

import pandas as pd

import numpy as np
from google.colab import drive
drive.mount('/content/drive')

import numpy as np
from google.colab import drive
drive.mount('mydrive')

from google.colab import drive
drive.mount('/content/drive')

data = ('/content/drive/MyDrive/TFM - Palladium/Palladium_Data_Set_pre_EDA.csv')
df_data = pd.read_csv(data, sep=",")
df_data

cols_to_drop = ['ID_RESERVA','LOCALIZADOR','ID_REGIMEN','ID_TIPO','ID_VIAJACON','TIPOGRATIS','TIPODOCUMENTO']

df_data_clean= df_data.drop(cols_to_drop, axis=1)

cols_to_drop = ["ATENCION","LOC_COMPARTIDA","GRUPOCARAC","HABITACION","VUELOSALIDA","STAMP","ID_CARDEX","HORALLEGADAVUELO","HORASALIDAVUELO","VUELOSALIDA","CLIENTE2","PAGO","GRUPO","TIPOGRATIS","LOCALIZADORPLUS","ID_DEPCITY","DEPCITY","AUTORIZO","CONFIDENCIAL","AUTORIZADOPOR","ACUERDO","AUTORIZACION","ID_TIPO","ID_REGIMEN","ID_RESERVA","ID_CLIENTE", "ID_CLIENTE2", "TIPO_CLIENTE2","CLIENTE2", "ID_HISTORICO", "ID_GRUPO", "ID_MULTIPLE", "ID_CRS", "CRS", "ID_GDS", "GDS", "ID_TTOO", "TTOO", "ID_CONTRATO", "ID_MONEDA", "ID_TIPO_FACTURA","ID_HABITACION","ID_COMPARTIDA","ID_GRUPOCARAC","ID_CUPO","FECHA_TOMA","HORA_TOMA","HORA_LLEGADA","HORA_SALIDA","HORA_LIMITE","ID_SEGMENTO","ID_FUENTE","ID_ATENCION","ID_FIDELIDAD","ID_SEGMENTOCREDITO","ID_TRATO","ID_PAIS","ID_PAGO","ID_REGFACTURA","ID_CONTACTO"]

df_data_clean= df_data.drop(cols_to_drop, axis=1)

#Creación Comercializadora
df_data_clean['Price_Comercializadora'] = (df_data_clean['CMVALHAB']+df_data_clean['CMVALPEN'])+df_data_clean['CMCVALSERV']
df_data_clean.head()

#Creación de la variable Price
df_data_clean['Price'] = (df_data_clean['VALHAB']+df_data_clean['VALPEN'])+df_data_clean['VALSERV']+df_data_clean["VALFIJOS"]
df_data_clean.head()

df_data_clean.describe()

df_data_clean["ID_HOTEL"].value_counts()

#Visualizar cuantas celdas no tienen "Sin país"
df_data_clean["PAIS"].value_counts()

df_data_clean.replace(["nan","Sin País"], "DESCONOCIDO")

df_data_clean["PAIS"].fillna("DESCONOCIDO")

#Debido a que "nan" y "Sin País" afecta al modelo, decidimos crear una nueva categoía unificando ambos y sustituyendo por "DESCONOCIDO"
df_data_clean["PAIS"]= df_data_clean["PAIS"].fillna("DESCONOCIDO")

#Debido a que "nan" y "Sin País" afecta al modelo, decidimos crear una nueva categoía unificando ambos y sustituyendo por "DESCONOCIDO"
df_data_clean["PAIS"]= df_data_clean["PAIS"].replace(to_replace=["Sin País"],value=["DESCONOCIDO"])

#Comprobamos que ue "nan" y "Sin País" se ha sustituido por "DESCONOCIDO"
df_data_clean["PAIS"].unique()

df_data_clean["ESTADO_RESERVA"]= df_data_clean["STATUS"].replace(to_replace=[1,2,3,4,5],value=[1,1,0,0,0])

filtro=df_data_clean['ESTADO_RESERVA']<9
df_data_clean_sin_nueve=df_data_clean[filtro]

df_data_clean_sin_nueve['ESTADO_RESERVA'].unique

df_data_clean=df_data_clean_sin_nueve

print(df_data_clean["ESTADO_RESERVA"].head(15))

df_data_clean["ID_HOTEL"].unique()

df_data_clean.groupby('STATUS')[['ID_HOTEL','Price']].mean().reset_index().sort_values(['ID_HOTEL','Price'], ascending=False).head(20)

df_data_clean['CANELACION'] = df_data_clean['STATUS']=3
df_data_clean.head()

df_data_clean['SALIDA'] = pd.to_datetime(df_data_clean['SALIDA'])

df_data_clean['LLEGADA'] = pd.to_datetime(df_data_clean['LLEGADA'])
df_data_clean.dtypes

df_data_clean.head(5)

df_data_clean.loc[(df_data_clean['ADULTOS']==2) & (df_data_clean['NENES']==0) & (df_data_clean['BEBES']==0), 'TARGET'] = 'PAREJAS'

df_data_clean



df_data_clean.loc[(df_data_clean['ADULTOS']==2) & (df_data_clean['NENES']) + (df_data_clean['BEBES']>0), 'TARGET'] = 'FAMILIA'

df_data_clean.loc[(df_data_clean['ADULTOS']==1) & (df_data_clean['NENES']==0) & (df_data_clean['BEBES']==0), 'TARGET'] = 'INDIVIDUAL'

from google.colab import files
df_data_clean.to_csv('filename.csv') 
files.download('filename.csv')